export const FETCH_FAVORITES_DOGS=" FETCH_FAVORITES_DOGS";
export const FETCH_ERRORS="FETCH_ERRORS";
export const REMOVE_FAVORITE_DOGS="REMOVE_FAVORITE_DOGS";
export const ADD_FAVORITE_DOGS="ADD_FAVORITE_DOGS";
export const DISABLE_BUTTON_BY_ID="DISABLE_BUTTON_BY_ID";
export const LOADING_STARTS="LOADING_STARTS";
export const ENABLE_BUTTON_BY_ID=" ENABLE_BUTTON_BY_ID"
